name: AbyssIrc Build docker image

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

  build-and-publish-docker:
    name: Build and Publish Docker Image
    needs: test
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract project version
        id: project-version
        run: |
          VERSION=$(grep -oP '<Version>\K[^<]+' src/AbyssIrc.Server/AbyssIrc.Server.csproj || echo "0.0.1")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Build Docker image
        run: |
          docker build -t tgiachi/abyssirc-server:latest -t tgiachi/abyssirc-server:${{ steps.project-version.outputs.VERSION }} .

      - name: Push Docker image
        run: |
          docker push tgiachi/abyssirc-server:latest
          docker push tgiachi/abyssirc-server:${{ steps.project-version.outputs.VERSION }}
